'use client';

import { useSearchParams } from 'next/navigation';
import { useEffect, useState, Suspense } from 'react';
import { SafetyReport } from '@/types';
import ReportCard from '@/components/ReportCard';
import Link from 'next/link';

function ReportContent() {
  const searchParams = useSearchParams();
  const input = searchParams.get('input');
  const [report, setReport] = useState<SafetyReport | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    if (!input) {
      setLoading(false);
      setError('No input provided. Go back to the scanner to run a scan.');
      return;
    }

    const runScan = async () => {
      try {
        const response = await fetch('/api/scan', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ input }),
        });

        if (!response.ok) {
          throw new Error('Scan failed');
        }

        const data: SafetyReport = await response.json();
        setReport(data);
      } catch {
        setError('Failed to generate report. Please try again.');
      } finally {
        setLoading(false);
      }
    };

    runScan();
  }, [input]);

  const handleCopyReport = () => {
    if (!report) return;
    const lines = [
      `=== ChainShield Safety Report ===`,
      `Input: ${report.inputValue}`,
      `Type: ${report.inputType}`,
      `Risk Score: ${report.riskScore}/100`,
      `Risk Level: ${report.riskLevel}`,
      `Confidence: ${report.confidence}`,
      ``,
      `--- Verdict ---`,
      report.summary,
      ``,
      `--- Findings ---`,
      ...report.findings.map(f => `[${f.severity.toUpperCase()}] ${f.message}`),
      ``,
      `--- Score Breakdown ---`,
      ...report.scoreBreakdown.map(b => `  ${b.label}: +${b.scoreImpact}`),
      ``,
      ...(report.nextStep ? [`--- Next Step ---`, report.nextStep, ``] : []),
      `--- Recommendations ---`,
      ...report.recommendations.map(r => `• ${r}`),
      ``,
      `Generated by ChainShield`,
    ];
    navigator.clipboard.writeText(lines.join('\n')).catch(() => {
      // Clipboard API unavailable
    });
  };

  if (loading) {
    return (
      <div className="min-h-[60vh] flex flex-col items-center justify-center gap-4">
        <div className="w-10 h-10 border-[3px] border-blue-500 border-t-transparent rounded-full animate-spin" />
        <p className="text-gray-500 text-sm">Generating report...</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-[60vh] flex flex-col items-center justify-center gap-5">
        <p className="text-red-400 text-sm">{error}</p>
        <Link
          href="/"
          className="px-5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white rounded-xl text-sm font-medium transition-colors"
        >
          Go to Scanner
        </Link>
      </div>
    );
  }

  if (!report) return null;

  return (
    <div className="max-w-3xl mx-auto px-6 py-12">
      <Link href="/" className="text-gray-500 hover:text-gray-300 text-sm mb-8 inline-flex items-center gap-1.5 transition-colors">
        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
        </svg>
        Back to Scanner
      </Link>
      <ReportCard
        report={report}
        onCopyReport={handleCopyReport}
        onNewScan={() => window.location.href = '/'}
      />
    </div>
  );
}

export default function ReportPage() {
  return (
    <Suspense fallback={
      <div className="min-h-[60vh] flex flex-col items-center justify-center gap-4">
        <div className="w-10 h-10 border-[3px] border-blue-500 border-t-transparent rounded-full animate-spin" />
        <p className="text-gray-500 text-sm">Loading...</p>
      </div>
    }>
      <ReportContent />
    </Suspense>
  );
}
