'use client';

import { useState, useEffect, useCallback } from 'react';
import { SafetyReport, RiskLevel } from '@/types';
import ScanForm from '@/components/ScanForm';
import ReportCard from '@/components/ReportCard';

interface RecentScan {
  input: string;
  inputType: string;
  riskLevel: RiskLevel;
  riskScore: number;
  timestamp: string;
}

const HISTORY_KEY = 'chainshield_recent';
const MAX_HISTORY = 5;

function getRecentScans(): RecentScan[] {
  try {
    const raw = sessionStorage.getItem(HISTORY_KEY);
    return raw ? JSON.parse(raw) : [];
  } catch {
    return [];
  }
}

function saveRecentScan(report: SafetyReport) {
  try {
    const scans = getRecentScans().filter(s => s.input !== report.inputValue);
    scans.unshift({
      input: report.inputValue,
      inputType: report.inputType,
      riskLevel: report.riskLevel,
      riskScore: report.riskScore,
      timestamp: report.timestamp,
    });
    sessionStorage.setItem(HISTORY_KEY, JSON.stringify(scans.slice(0, MAX_HISTORY)));
  } catch {
    // sessionStorage unavailable
  }
}

const inputTypeLabels: Record<string, string> = {
  url: 'URL',
  token: 'Token',
  txHash: 'Tx',
  wallet: 'Wallet',
  btcWallet: 'BTC',
  unknown: '?',
};

const levelColors: Record<string, string> = {
  SAFE: 'text-emerald-400 border-emerald-500/20 bg-emerald-500/5',
  SUSPICIOUS: 'text-yellow-400 border-yellow-500/20 bg-yellow-500/5',
  DANGEROUS: 'text-red-400 border-red-500/20 bg-red-500/5',
};

function formatReportText(report: SafetyReport): string {
  const lines = [
    `=== ChainShield Safety Report ===`,
    `Input: ${report.inputValue}`,
    `Type: ${report.inputType}`,
    `Risk Score: ${report.riskScore}/100`,
    `Risk Level: ${report.riskLevel}`,
    `Confidence: ${report.confidence}`,
    ``,
    `--- Verdict ---`,
    report.summary,
    ``,
    `--- Findings ---`,
    ...report.findings.map(f => `[${f.severity.toUpperCase()}] ${f.message}`),
    ``,
    `--- Score Breakdown ---`,
    ...report.scoreBreakdown.map(b => `  ${b.label}: +${b.scoreImpact}`),
    ``,
    ...(report.nextStep ? [`--- Next Step ---`, report.nextStep, ``] : []),
    `--- Recommendations ---`,
    ...report.recommendations.map(r => `• ${r}`),
    ``,
    `Scanned at: ${new Date(report.timestamp).toLocaleString()}`,
    `Generated by ChainShield`,
  ];
  return lines.join('\n');
}

function shortenInput(input: string, type: string): string {
  if (type === 'url') return input.replace(/^https?:\/\//, '').slice(0, 30);
  if (input.length > 16) return `${input.slice(0, 6)}...${input.slice(-4)}`;
  return input;
}

export default function Home() {
  const [report, setReport] = useState<SafetyReport | null>(null);
  const [scanning, setScanning] = useState(false);
  const [copied, setCopied] = useState(false);
  const [recentScans, setRecentScans] = useState<RecentScan[]>([]);

  useEffect(() => {
    setRecentScans(getRecentScans());
  }, []);

  const handleScanComplete = useCallback((r: SafetyReport) => {
    setReport(r);
    setScanning(false);
    saveRecentScan(r);
    setRecentScans(getRecentScans());
  }, []);

  const handleCopyReport = () => {
    if (!report) return;
    navigator.clipboard.writeText(formatReportText(report))
      .then(() => {
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
      })
      .catch(() => {
        // Clipboard API unavailable
      });
  };

  const handleNewScan = () => {
    setReport(null);
    setScanning(false);
  };

  return (
    <div className="min-h-[calc(100vh-120px)] flex flex-col items-center justify-center px-4 sm:px-6 py-16">
      {!report && !scanning && (
        <div className="text-center mb-12 hero-glow relative z-10">
          {/* Brand */}
          <div className="flex items-center justify-center gap-2.5 mb-6">
            <svg className="w-8 h-8 text-blue-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
            </svg>
            <span className="text-lg font-semibold text-gray-200 tracking-tight">ChainShield</span>
          </div>

          <h1 className="text-4xl sm:text-5xl font-bold text-white mb-4 tracking-tight leading-tight">
            Crypto safety checks<br className="hidden sm:block" /> without tracking
          </h1>
          <p className="text-base text-gray-400 max-w-lg mx-auto leading-relaxed">
            Paste a URL, token contract, transaction hash, or wallet address. Get an instant safety report.
          </p>
        </div>
      )}

      {!report && (
        <ScanForm
          onScanComplete={handleScanComplete}
          onScanStart={() => setScanning(true)}
        />
      )}

      {/* Recent Scans — shown on homepage when not scanning */}
      {!report && !scanning && recentScans.length > 0 && (
        <div className="w-full max-w-2xl mx-auto mt-8">
          <p className="text-[11px] text-gray-600 uppercase tracking-widest mb-2.5 text-center">Recent scans (this session)</p>
          <div className="flex flex-wrap gap-2 justify-center">
            {recentScans.map((scan) => (
              <button
                key={scan.input + scan.timestamp}
                onClick={() => {
                  setScanning(true);
                  // Re-trigger scan via the API
                  fetch('/api/scan', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ input: scan.input }),
                  })
                    .then(res => res.json())
                    .then((r: SafetyReport) => handleScanComplete(r))
                    .catch(() => setScanning(false));
                }}
                className={`inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg border text-xs font-medium transition-colors hover:bg-gray-800/50 ${levelColors[scan.riskLevel]}`}
              >
                <span className="text-gray-500">{inputTypeLabels[scan.inputType] || '?'}</span>
                <span className="font-mono">{shortenInput(scan.input, scan.inputType)}</span>
                <span className="tabular-nums">{scan.riskScore}</span>
              </button>
            ))}
          </div>
        </div>
      )}

      {scanning && !report && (
        <div className="w-full max-w-3xl mx-auto mt-10 space-y-4 animate-pulse">
          {/* Score header skeleton */}
          <div className="glass-card rounded-2xl p-6 sm:p-8">
            <div className="flex flex-col sm:flex-row items-center gap-6 sm:gap-8">
              <div className="w-28 h-28 rounded-full bg-gray-800 flex-shrink-0" />
              <div className="flex-1 space-y-3 w-full">
                <div className="flex gap-2 justify-center sm:justify-start">
                  <div className="h-6 w-28 bg-gray-800 rounded-full" />
                  <div className="h-6 w-36 bg-gray-800 rounded-full" />
                </div>
                <div className="h-3 w-20 bg-gray-800 rounded mx-auto sm:mx-0" />
                <div className="h-4 w-48 bg-gray-800 rounded mx-auto sm:mx-0" />
              </div>
            </div>
          </div>
          {/* Summary skeleton */}
          <div className="rounded-2xl p-5 border border-gray-800 bg-gray-800/20">
            <div className="flex items-start gap-3.5">
              <div className="w-5 h-5 bg-gray-800 rounded-full flex-shrink-0 mt-0.5" />
              <div className="flex-1 space-y-2">
                <div className="h-4 w-3/4 bg-gray-800 rounded" />
                <div className="h-3 w-1/2 bg-gray-800 rounded" />
              </div>
            </div>
          </div>
          {/* Findings skeleton */}
          <div className="glass-card rounded-2xl p-5">
            <div className="h-3 w-16 bg-gray-800 rounded mb-4" />
            <div className="space-y-2">
              <div className="h-10 bg-gray-800/50 rounded-xl" />
              <div className="h-10 bg-gray-800/50 rounded-xl" />
            </div>
          </div>
          {/* Spinner text */}
          <div className="flex flex-col items-center gap-3 pt-2">
            <div className="w-8 h-8 border-[3px] border-blue-500 border-t-transparent rounded-full animate-spin" />
            <p className="text-gray-500 text-sm">Analyzing for risk signals...</p>
          </div>
        </div>
      )}

      {report && (
        <div className="w-full animate-fade-in-up">
          <ReportCard
            report={report}
            onCopyReport={handleCopyReport}
            onNewScan={handleNewScan}
          />
          {copied && (
            <p className="text-center text-emerald-400 text-sm mt-4 animate-fade-in-up">Report copied to clipboard!</p>
          )}
        </div>
      )}
    </div>
  );
}
